// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pratik_Survivor.Context;

#nullable disable

namespace Pratik_Survivor.Migrations
{
    [DbContext(typeof(SurvivorDbContext))]
    [Migration("20241006120629_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pratik_Survivor.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 6, 15, 6, 29, 199, DateTimeKind.Local).AddTicks(5138),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 10, 6, 15, 6, 29, 199, DateTimeKind.Local).AddTicks(5147),
                            Name = "Ünlüler"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 6, 15, 6, 29, 199, DateTimeKind.Local).AddTicks(5149),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 10, 6, 15, 6, 29, 199, DateTimeKind.Local).AddTicks(5149),
                            Name = "Gönüllüler"
                        });
                });

            modelBuilder.Entity("Pratik_Survivor.Entities.CompetitorsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Competitors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 10, 6, 15, 6, 29, 199, DateTimeKind.Local).AddTicks(5231),
                            FirstName = "Acun",
                            IsDeleted = false,
                            LastName = "Ilıcalı",
                            ModifiedDate = new DateTime(2024, 10, 6, 15, 6, 29, 199, DateTimeKind.Local).AddTicks(5231)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 10, 6, 15, 6, 29, 199, DateTimeKind.Local).AddTicks(5233),
                            FirstName = "Aleyna",
                            IsDeleted = false,
                            LastName = "Avcı",
                            ModifiedDate = new DateTime(2024, 10, 6, 15, 6, 29, 199, DateTimeKind.Local).AddTicks(5234)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 10, 6, 15, 6, 29, 199, DateTimeKind.Local).AddTicks(5235),
                            FirstName = "Hadise",
                            IsDeleted = false,
                            LastName = "Açıkgöz",
                            ModifiedDate = new DateTime(2024, 10, 6, 15, 6, 29, 199, DateTimeKind.Local).AddTicks(5235)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 10, 6, 15, 6, 29, 199, DateTimeKind.Local).AddTicks(5236),
                            FirstName = "Sertan",
                            IsDeleted = false,
                            LastName = "Bozkuş",
                            ModifiedDate = new DateTime(2024, 10, 6, 15, 6, 29, 199, DateTimeKind.Local).AddTicks(5236)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 10, 6, 15, 6, 29, 199, DateTimeKind.Local).AddTicks(5237),
                            FirstName = "Özge",
                            IsDeleted = false,
                            LastName = "Açık",
                            ModifiedDate = new DateTime(2024, 10, 6, 15, 6, 29, 199, DateTimeKind.Local).AddTicks(5237)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 10, 6, 15, 6, 29, 199, DateTimeKind.Local).AddTicks(5238),
                            FirstName = "Kıvanç",
                            IsDeleted = false,
                            LastName = "Tatlıtuğ",
                            ModifiedDate = new DateTime(2024, 10, 6, 15, 6, 29, 199, DateTimeKind.Local).AddTicks(5239)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 10, 6, 15, 6, 29, 199, DateTimeKind.Local).AddTicks(5239),
                            FirstName = "Ahmet",
                            IsDeleted = false,
                            LastName = "Yılmaz",
                            ModifiedDate = new DateTime(2024, 10, 6, 15, 6, 29, 199, DateTimeKind.Local).AddTicks(5240)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 10, 6, 15, 6, 29, 199, DateTimeKind.Local).AddTicks(5240),
                            FirstName = "Elif",
                            IsDeleted = false,
                            LastName = "Demirtaş",
                            ModifiedDate = new DateTime(2024, 10, 6, 15, 6, 29, 199, DateTimeKind.Local).AddTicks(5241)
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 10, 6, 15, 6, 29, 199, DateTimeKind.Local).AddTicks(5241),
                            FirstName = "Cem",
                            IsDeleted = false,
                            LastName = "Öztürk",
                            ModifiedDate = new DateTime(2024, 10, 6, 15, 6, 29, 199, DateTimeKind.Local).AddTicks(5242)
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 10, 6, 15, 6, 29, 199, DateTimeKind.Local).AddTicks(5243),
                            FirstName = "Ayşe",
                            IsDeleted = false,
                            LastName = "Karaca",
                            ModifiedDate = new DateTime(2024, 10, 6, 15, 6, 29, 199, DateTimeKind.Local).AddTicks(5243)
                        });
                });

            modelBuilder.Entity("Pratik_Survivor.Entities.CompetitorsEntity", b =>
                {
                    b.HasOne("Pratik_Survivor.Entities.CategoryEntity", "Category")
                        .WithMany("Competitors")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Pratik_Survivor.Entities.CategoryEntity", b =>
                {
                    b.Navigation("Competitors");
                });
#pragma warning restore 612, 618
        }
    }
}
